### ISSUE TITLE
How to use it in composition API

### ISSUE THREAD

**Issue by demiro** [kuroski/v-eager#1]
Hello, how would I go to use it inside the vue 3 and composition api?

**Comment by kuroski** [comment]
Hello @demiro, how are you?

So, this directive was made for Vue 2, I don't know if it would run in a Vue 3 environment.

The code does not have a hard dependency on Vue 2, but you might face some problems installing it. 

I don't know if it would work normally for Vue 3 projects... But please let me know if you are facing any problems with that and I might be able to help out.

---

Regarding usage with composition API:

- You can [install it globally](https://github.com/kuroski/v-eager#global) and [use](https://github.com/kuroski/v-eager#usage) (please let me know if you're facing problems with Vue 3, because I'll have to port the library to enable that then)
- You can just [mix-and-match options API](https://github.com/kuroski/v-eager#local) with composition API then [just use](https://github.com/kuroski/v-eager#usage)
```javascript
import { eager } from '@kuroski/v-eager'

export default {
  directive: { eager },
  setup() {},
}
```

- If you use `<script setup>`
```vue
<script setup>
import { eager } from '@kuroski/v-eager'
</script>

<template>
  <!-- This should work, I think 😅 -->
  <input v-eager />
</template>
```
- You can try to add it manually globally in Vue 3
```javascript
import { eager } from '@kuroski/v-eager'

const app = createApp({})
app.directive('eager', eager)
```
---

❗❗ Please don't forget to check this comment ❗❗
https://github.com/vuejs/vue/issues/9777#issuecomment-619567916

I created this directive to "force" solving the problem, but I managed to solve my problem without using it, please check it out before trying anything else, and let me know if it solved your problem 😄

**Comment by kuroski** [comment]
I'm gonna close this issue for now since I didn't receive any response in a while.
If you are still having problems, feel free to re-open it 😄
